name: ci-staging

on:
  pull_request:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint HTML
        run: npm run lint:html

      - name: Lint CSS
        run: npm run lint:css

      - name: Build with Parcel
        run: npm run build

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pakvista-cicd:staging-latest

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista-cicd:staging-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista-cicd:staging-${{ github.sha }}